### ISSUE TITLE
error[E0603]: module `collections` is private/error[E0283]: type annotations needed !! Need a help!! to solve this issue!!

### ISSUE THREAD

**Issue by shumshersubashgautam** [realnimish/polkadot-amm#2]
[1/1] Running tests
   Compiling amm v0.1.0 (/home/subash/polkadot/AMM/amm)
error[E0603]: module `collections` is private
  --> lib.rs:12:22
   |
12 |     use ink_storage::collections::HashMap;
   |                      ^^^^^^^^^^^ private module
   |
note: the module `collections` is defined here

error[E0283]: type annotations needed
  --> lib.rs:41:9
   |
35 |     #[derive(Default)]
   |              ------- in this derive macro expansion
...
41 |         shares: HashMap<AccountId, Balance>, // Stores the share holding of each provider
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `_: Default`
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0283, E0603.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `amm` due to 2 previous errors
ERROR: `"/home/subash/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "test" ""` failed with exit code: Some(101)

**Comment by realnimish** [comment]
HashMap has been removed in the latest version of ink! You can replace it with Mapping to resolve it

**Comment by shumshersubashgautam** [comment]
Thanks for ur help man!! but it's solved with hashmap finally!! can u give me the test faucet link to get test tokens its expired link which u have kept in the tutorial??

**Comment by realnimish** [comment]
You can try the Beresheet testnet (Edgeware).

Endpoint: https://docs.edgeware.wiki/resources/networks
Faucet: https://faucet-beresheet.vercel.app/
